# permissions for end users to view baremetalnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bamel-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: baremetalnode-viewer-role
rules:
- apiGroups:
  - bamel.baremetal.io
  resources:
  - baremetalnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bamel.baremetal.io
  resources:
  - baremetalnodes/status
  verbs:
  - get
