# permissions for end users to edit nodepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bamel-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: nodepool-editor-role
rules:
- apiGroups:
  - bamel.baremetal.io
  resources:
  - nodepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bamel.baremetal.io
  resources:
  - nodepools/status
  verbs:
  - get
