apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- etcd-deployment.yaml

namePrefix: bamel-

commonLabels:
  app.kubernetes.io/name: bamel-etcd
  app.kubernetes.io/component: etcd